.model small

.stack 256
	
.data

;========================Variables declaradas aqui===========================
LET 	db "SUERTE CHICOS A TRABAJAR",'$'	;LETRERO A DESPLEGAR
MSG 	DB	"--MINI PIANO--", '$'
NL db 10,13, '$'							;PREPARA SALTO DE LINEA
MSG1   	DB 	"#NOTA: PRECIONAR 1 PARA SALIR#", '$'
CONT2	EQU 042H							;DIR DEL CONTADOR 2
DIR_CW	EQU  043H							; DIR PALABRA DE CONTROL.
CW		EQU 0B6H							;PALABRA DE CONTROL PARA MODO 3 16BITS DE ACCESO EN MODO BINARIO. 
RBCW	EQU 0E8H							; READBACK COMMAND
CONFIG  DB  0
FREC	DW	0								;FRECUENCIA DE SONIDO

;============================================================================

.code
main:	mov ax,@data
	mov ds,ax
	mov es, ax                  ;set segment register
    and sp, not 3               ;align stack to avoid AC fault

	
;====================================Código==================================  
MOV DX,CONT2					;DIR DEL CONTADOR 2
IN AL,DX						;LEO CONFIGURACION DEL CONTADOR
MOV CONFIG,AL					;SALVO CONFIGURACION PREVIA

MOV AH, 09H						;ACTIVA INSTRUCCION PARA ESCRIBIR UN MENSAJE EN PANTALLA
MOV DX, OFFSET MSG				;EL OFFSET DE MSG SE LE PASA A DX PARA PROCESARLO
INT 21H							;INTERRUPCION PARA ENVIAR EL MENSAJE A PANTALLA

MOV AH, 09H
MOV DX, OFFSET NL				;IMPRIMIR SALTODO DE LINEA
INT 21H

MOV AH, 09H						;ACTIVA INSTRUCCION PARA ESCRIBIR UN MENSAJE EN PANTALLA
MOV DX, OFFSET MSG1				;EL OFFSET DE MSG1 LO TOMA DX PARA PROCESARLO
INT 21H							;INTERRUPCION PARA ENVIAR EL MENSAJE A PANTALLA

MOV AH, 09H
MOV DX, OFFSET NL				;IMPRIMIR SALTO DE LINEA
INT 21H

;
;CICLO QUE VERIFICA SI UNA TECLA ESTA PULSADA
;
KEY_PRESS:
	MOV AH, 01H					;ACTIVAR INSTRUCCION PARA ESCRIBIR CARACTER POR CARACTER
	INT 21H						;INTERRUPCION PARA LA CAPTURA DEL VALOR
	
	;CONJUNTO DE COMPARACIONES PARA SABER SI LAS TECLAS REQUERIDAS
	;PARA EL PIANO HAN DISO PULSADAS
	CMP AL, '1'					;COMPARA SI LA TECLA PULSADA ES 1 
	JE EXITC					;SI ES UNO SALE DEL PROGRAMA
	CMP	AL, 'q'					;SI AL ES IGUAL A Q ENTONCES SALTA A LA ETIQUETA QUE LLAMA A LA FUNCION QUE GENERA EL SONIDO
	JE	KEY_QC
	CMP AL, 'w'
	JE KEY_WC
	CMP AL, 'e'
	JE KEY_EC
	CMP AL, 'r'
	JE KEY_RC
	CMP AL, 't'
	JE KEY_TC
	CMP AL, 'y'
	JE KEY_YC
	CMP AL, 'u'
	JE KEY_UC
	CMP AL, 'i'
	JE KEY_IC
	CMP AL, 'o'
	JE KEY_OC
	CMP AL, 'p'
	JE KEY_PC
	CMP AL, 'a'
	JE KEY_AC
	CMP AL, 's'
	JE KEY_SC
	CMP AL, 'd'
	JE KEY_DC
	CMP AL, 'f'
	JE KEY_FC
	CMP AL, 'g'
	JE KEY_GC
	CMP AL, 'h'
	JE KEY_HC
	CMP AL, 'j'
	JE KEY_JC
	CMP AL, 'k'
	JE KEY_KC
	CMP AL, 'l'
	JE KEY_LC
	JMP KEY_PRESS


;
;ETIQUETAS QUE PERMITEN HACER EL SALTO CUANDO SE QUIERE EJECUTAR UN SONIDO
;ES EL MISMO PROCESO PARA TODAS LAS DEMAS ETIQUETAS
;
EXITC:
	JMP EXIT
KEY_QC:
	CALL KEY_Q					;LLAMA LA FUNCION DEL SONIDO CUANDO SE PULSA  Q
	JMP KEY_PRESS
KEY_WC:
	CALL KEY_W					;LLAMA LA FUNCION DEL SONIDO CUANDO SE PULSA W
	JMP KEY_PRESS
KEY_EC:
	CALL KEY_E
	JMP KEY_PRESS
KEY_RC:
	CALL KEY_R
	JMP KEY_PRESS
KEY_TC:
	CALL KEY_T
	JMP KEY_PRESS
KEY_YC:
	CALL KEY_Y
	JMP KEY_PRESS
KEY_UC:
	CALL KEY_U
	JMP KEY_PRESS
KEY_IC:
	CALL KEY_I
	JMP KEY_PRESS
KEY_OC:
	CALL KEY_O
	JMP KEY_PRESS
KEY_PC:
	CALL KEY_P
	JMP KEY_PRESS
KEY_AC:
	CALL KEY_A
	JMP KEY_PRESS
KEY_SC:
	CALL KEY_S
	JMP KEY_PRESS
KEY_DC:
	CALL KEY_D
	JMP KEY_PRESS
KEY_FC:
	CALL KEY_F
	JMP KEY_PRESS
KEY_GC:
	CALL KEY_G
	JMP KEY_PRESS
KEY_HC:
	CALL KEY_H
	JMP KEY_PRESS
KEY_JC:
	CALL KEY_J
	JMP KEY_PRESS
KEY_KC:
	CALL KEY_K
	JMP KEY_PRESS
KEY_LC:
	CALL KEY_L
	JMP KEY_PRESS

;--------- Program Exit
EXIT:           
    MOV     AX,4c00h                ; terminate program
    INT     21h
 
;--------- Place your functions here


;
;AQUI ESTAN LAS FUNCIONES QUE GENERAN LOS SONIDOS
;ES EL MISMO PROCESO PARA CADA UNO DE LOS SONIDOS
;
KEY_Q:
	MOV AX, 523						;PASA FRECUENCIA A AX
	MOV FREC, AX					;SE LE ASIGNA A FREC EL VALOR DE AX
	CALL PIANO						;SE LLAMA LA FUNCION PIANO PARA QUE GENERE EL SONIDO
	RET								;RETORNA EL CONTROL AL SISTEMA
	
KEY_W:
	MOV AX, 582
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_E:
	MOV AX, 659
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_R:
	MOV AX, 698
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_T:
	MOV AX, 784
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_Y:
	MOV AX, 880
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_U:
	MOV AX, 988
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_I:
	MOV AX, 554
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_O:
	MOV AX, 622
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_P:
	MOV AX, 740
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_A:
	MOV AX, 229
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_S:
	MOV AX, 923
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_D:
	MOV AX, 261
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_F:
	MOV AX, 293
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_G:
	MOV AX, 329
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_H:
	MOV AX, 349
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_J:
	MOV AX, 392
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_K:
	MOV AX, 466
	MOV FREC, AX
	CALL PIANO
	RET
	
KEY_L:
	MOV AX, 498
	MOV FREC, AX
	CALL PIANO
	RET
	
;
;MANDA EL SONIDO A LAS BOCINAS
;
PIANO:
	MOV DX, 43H						;DIRECCION DE DISPOSITIVO DE ENTRADA SALIDA
	MOV AL,RBCW						;READBACK COMMAND, PIDE LA CONFIGURACION 
	OUT DX,AL						;ESCRITURA HACIA DISPOSITIVO DE ENTRADA SALIDA
	NOP	
	NOP
	
	MOV DX, 43H						;DIRECCION DE DISPOSITIVO DE ENTRADA SALIDA
	MOV AL,CW						;
	OUT DX,AL						;ESCRITURA HACIA DISPOSITIVO DE ENTRADA SALIDA
	MOV AX, FREC					;EL TONO SE LE ENVIA AL DISPOSITIVO ENTRADA SALIDA
	OUT CONT2, AL					;ENVIA EL LSB
	MOV AL, AH						;MUEVE EL MSB A AL
	OUT CONT2, AL					;LO GUARDA
	
	IN	AL, 61H						;VA AL PUERTO 61 STATE
	OR 	AL, 03H						;PRENDE LAS BOCINAS
	OUT 61H, AL						;BOCINAS PRENDIDAS
	CALL RETARDO					;DELAY DEL SONIDO
	AND AL, 0FCH					;LIMPIA EL ACTIVADOR DE LAS BOCINAS
	OUT 61H, AL						;BOCINAS APAGADAS
	
	MOV AL,0DCH						;PARTE DE BAJA DEL CONTEO 11DC
	MOV DX, CONT2					;DIRECCION DEL OCNTADOR 2.
	OUT DX,AL						;ENVIO CONTEO.

	MOV AL,011H						;PARTE DE ALTA DEL CONTEO 11DC
	MOV DX, CONT2					;DIRECCION DEL OCNTADOR 2.
	OUT DX,AL						;ENVIO CONTEO.
	RET


;LIMPIAR_KEYBOARD:
;	PUSH ES							;GUARDA ES
;	PUSH DI							;GUARDA ES
;	MOV  AX, 40H					;SEGMENTO DEL BIOS EN AX
;	MOV  ES, AX						;PASA EL SEGMENTO A ES
;	MOV  AX, 1AH					;PUNTERO DEL TECLADO 
;	MOV  DI, AX						;SE TRANSFIERE A DI
;	MOV  AX, 1EH					;EMPIEZA EL BUFFER DEL TECLADO EN AX
;	MOV  ES: WORD PTR [DI], AX		;SE TRANSFIERE A LA CABEZA DEL PUNTERO
;	INC  DI							
;	INC  DI
;	MOV  ES: WORD PTR [DI], AX
;	POP  DI							;SACO DI DE LA PILA
;	POP  ES							;SACO ES DE LA PILA
;	RET

;FUNCION QUE GENERA UN RETARDO PARA CUANDO SE PULSE UNA TECLA
RETARDO:
    MOV AH, 00H						;ACTIVO EL TICK DEL TIMER
    INT 01AH						;LLAMA EL SERVICIO DEL TIMER BIOS
    ADD	DX,3						;VALOR DEL RETARDO A DX
    MOV BX, DX						;EL RESULTADO SE GUARDA EN BX
    
    OK:
    INT 01AH							
    CMP DX, BX						;SE PASA LA DURACION DEL RETARDO
    JL OK				
    RET  
        
;======================================================================
end main
